import { ORGAOS_LOA_NOMES } from "./secretarias-catalogo";

/**
 * Catálogo Canônico das Unidades Orçamentárias da LDO / LOA de Osasco
 * Mapeamento por chave 'SEC_COD.UNID_COD' (ex: '11.001', '09.008', '02.006')
 * Baseado na nomenclatura oficial desc_unid_orcamentaria da LDO.
 */
export const UNIDADES_ORCAMENTARIAS_LDO: Record<string, string> = {
  // 01 - CÂMARA MUNICIPAL DE OSASCO
  "01.001": "001 - CHEFIA DE GABINETE",

  // 02 - GABINETE DO PREFEITO
  "02.001": "001 - CHEFIA DE GABINETE",
  "02.006": "006 - FUNDO SOCIAL DE SOLIDARIEDADE",
  "02.012": "012 - FUNDO ESPECIAL DE MANUTENÇÃO DOS BOMBEIROS",

  // 04 - SECRETARIA DE FINANÇAS
  "04.001": "001 - GABINETE DA SECRETARIA DE FINANÇAS",

  // 05 - PROCURADORIA GERAL DO MUNICÍPIO
  "05.001": "001 - GABINETE DA PROCURADORIA GERAL DO MUNICÍPIO",

  // 06 - SECRETARIA DE ADMINISTRAÇÃO
  "06.001": "001 - GABINETE DA SECRETARIA DE ADMINISTRAÇÃO",
  "06.011": "011 - FUNDO MUNICIPAL DE VALORIZAÇÃO DOS SERVIDORES",

  // 07 - SECRETARIA DE EMPREGO, TRABALHO E RENDA
  "07.001": "001 - GABINETE DA SECRETARIA DE EMPREGO, TRABALHO E RENDA",
  "07.005": "005 - FUNDO MUNICIPAL DO TRABALHO",

  // 08 - SECRETARIA DA EDUCAÇÃO
  "08.001": "001 - GABINETE DA SECRETARIA DA EDUCAÇÃO",
  "08.006": "006 - SECRETARIA EXECUTIVA DE GESTÃO ESCOLAR",
  "08.007": "007 - SECRETARIA EXECUTIVA DE GESTÃO PEDAGÓGICA",
  "08.008": "008 - DIRETORIA GERAL DE GESTÃO ADMINISTRATIVA E FINANCEIRA",

  // 09 - SECRETARIA DA SAÚDE
  "09.001": "001 - GABINETE DA SECRETARIA DA SAÚDE",
  "09.006": "006 - HOSPITAL E MATERNIDADE MUNICIPAL AMADOR AGUIAR",
  "09.007": "007 - HOSPITAL MUNICIPAL ANTÔNIO GIGLIO",
  "09.008": "008 - DIRETORIA GERAL DE ATENÇÃO PRIMÁRIA EM SAÚDE",
  "09.009": "009 - DIRETORIA GERAL DA ATENÇÃO SECUNDÁRIA EM SAÚDE",
  "09.010": "010 - DIRETORIA GERAL DE URGÊNCIA E EMERGÊNCIA",
  "09.011": "011 - DEPARTAMENTO DE VIGILÂNCIA EM SAÚDE",
  "09.012": "012 - DEPARTAMENTO DE ASSISTÊNCIA FARMACÊUTICA",
  "09.015": "015 - DIRETORIA GERAL DA GESTÃO DE SAÚDE",

  // 11 - SECRETARIA DE SERVIÇOS E OBRAS
  "11.001": "001 - GABINETE DA SECRETARIA DE SERVIÇOS E OBRAS",
  "11.007": "007 - DEPTO DE OBRAS PÚBLICAS E INFRAESTRUTURA URBANA",
  "11.008": "008 - DIRETORIA GERAL DE SERVIÇOS URBANOS",
  "11.014": "014 - FUNDO MUNICIPAL DE MANUTENÇÃO DE VELÓRIOS",
  "11.017": "017 - DIRETORIA GERAL DE ILUMINAÇÃO PÚBLICA",
  "11.018": "018 - DIRETORIA GERAL DE GESTÃO DE RESÍDUOS",

  // 12 - SECRETARIA DE ESPORTE, RECREAÇÃO E LAZER
  "12.001": "001 - GABINETE DA SECRETARIA DE ESPORTE, RECREAÇÃO E LAZER",

  // 13 - SECRETARIA DE HABITAÇÃO
  "13.001": "001 - GABINETE DA SECRETARIA DE HABITAÇÃO",
  "13.008": "008 - FUNDO MUNICIPAL DE POLÍTICA URBANA E HABITACIONAL",

  // 14 - SECRETARIA DE ASSISTÊNCIA SOCIAL
  "14.001": "001 - GABINETE DA SECRETARIA DE ASSISTÊNCIA SOCIAL",
  "14.005": "005 - FUNDO MUNICIPAL DE ASSISTÊNCIA SOCIAL",
  "14.007": "007 - DEPARTAMENTO DE PROTEÇÃO SOCIAL BÁSICA",
  "14.008": "008 - DEPARTAMENTO DE PROTEÇÃO SOCIAL ESPECIAL",

  // 15 - SECRETARIA DA CULTURA
  "15.001": "001 - GABINETE DA SECRETARIA DE CULTURA",
  "15.002": "002 - RECURSOS SOB A SUPERVISÃO DA SECRETARIA DE CULTURA",
  "15.004": "004 - DEPARTAMENTO DE DIFUSÃO CULTURAL E ARTÍSTICA",

  // 16 - SECRETARIA DE TECNOLOGIA, INOVAÇÃO E DESENVOLVIMENTO ECONÔMICO
  "16.001": "001 - GABINETE DA SECRETARIA DE TECNOLOGIA, INOVAÇÃO E DESENVOLVIMENTO ECONÔMICO",

  // 17 - SECRETARIA DE MEIO AMBIENTE E RECURSOS HÍDRICOS
  "17.001": "001 - GABINETE DA SECRETARIA DE MEIO AMBIENTE E RECURSOS HÍDRICOS",
  "17.003": "003 - FUNDO MUNICIPAL DE MEIO AMBIENTE",

  // 18 - ENCARGOS GERAIS DO MUNICÍPIO
  "18.001": "001 - RECURSOS SOB A SUPERVISÃO DA SECRETARIA DE FINANÇAS",
  "18.002": "002 - RECURSOS SOB A SUPERVISÃO DA SECRETARIA DE ADMINISTRAÇÃO",
  "18.003": "003 - RECURSOS SOB A SUPERVISÃO DA SECRETARIA DE TECNOLOGIA, INOVAÇÃO E DESENVOLVIMENTO ECONÔMICO",

  // 19 - SECRETARIA DE TRANSPORTE E DA MOBILIDADE URBANA
  "19.001": "001 - GABINETE DA SECRETARIA DE TRANSPORTE E DA MOBILIDADE URBANA",
  "19.004": "004 - DEPARTAMENTO MUNICIPAL DE TRANSPORTES",
  "19.005": "005 - FUNDO MUNICIPAL DE TRÂNSITO",

  // 20 - SECRETARIA DE SEGURANÇA E CONTROLE URBANO
  "20.001": "001 - GABINETE DA SECRETARIA DE SEGURANÇA E CONTROLE URBANO",
  "20.006": "006 - COMANDO GERAL DA GUARDA CIVIL MUNICIPAL",

  // 21 - IPMO - INSTITUTO DE PREVIDÊNCIA
  "21.001": "001 - GABINETE DO IPMO",
  "21.003": "003 - RECURSOS PREVIDENCIÁRIOS DO IPMO",
  "21.005": "005 - FUNDO PREVIDENCIÁRIO DO IPMO",
  "21.006": "006 - BENEFÍCIOS PREVIDENCIÁRIOS DO IPMO",

  // 22 - FITO - FUNDAÇÃO INSTITUTO TECNOLÓGICO DE OSASCO
  "22.001": "001 - GABINETE DA FITO",
  "22.002": "002 - ADMINISTRAÇÃO GERAL - FITO",
  "22.003": "003 - ENSINO BÁSICO E TÉCNICO - FITO",
  "22.004": "004 - ENSINO SUPERIOR - FITO",
  "22.005": "005 - PROGRAMAS EDUCACIONAIS - FITO",
  "22.006": "006 - CONSERVATÓRIO MUSICAL - FITO",
  "22.007": "007 - CENTRO DE FORMAÇÃO - FITO",
  "22.008": "008 - GESTÃO OPERACIONAL - FITO",
  "22.009": "009 - APOIO AO ENSINO - FITO",
  "22.010": "010 - EXTENSÃO COMUNITÁRIA - FITO",
  "22.011": "011 - MANUTENÇÃO PATRIMONIAL - FITO",
  "22.012": "012 - FUNDO DE DESENVOLVIMENTO - FITO",
  "22.013": "013 - SERVIÇOS TÉCNICOS - FITO",
  "22.014": "014 - DESENVOLVIMENTO INSTITUCIONAL - FITO",
  "22.015": "015 - GESTÃO ACADÊMICA - FITO",
  "22.016": "016 - PROJETOS ESPECIAIS - FITO",

  // 23 - SECRETARIA DE COMUNICAÇÃO
  "23.001": "001 - GABINETE DA SECRETARIA DE COMUNICAÇÃO",

  // 24 - SECRETARIA DE PLANEJAMENTO E GESTÃO
  "24.001": "001 - GABINETE DA SECRETARIA DE PLANEJAMENTO E GESTÃO",

  // 27 - CONTROLADORIA GERAL DO MUNICÍPIO
  "27.001": "001 - GABINETE DA CONTROLADORIA GERAL DO MUNICÍPIO",

  // 28 - SECRETARIA DE GOVERNO
  "28.001": "001 - GABINETE DA SECRETARIA DE GOVERNO",
  "28.007": "007 - FUNDO MUNICIPAL DE POLÍTICAS SOBRE DROGAS",

  // 29 - SECRETARIA EXECUTIVA DA INFÂNCIA E JUVENTUDE
  "29.001": "001 - GABINETE DA SECRETARIA EXECUTIVA DA INFÂNCIA E JUVENTUDE",
  "29.002": "002 - RECURSOS SOB A SUPERVISÃO DA SECRETARIA DE ADMINISTRAÇÃO",

  // 30 - SECRETARIA EXECUTIVA DA PESSOA COM DEFICIÊNCIA
  "30.001": "001 - GABINETE DA SECRETARIA EXECUTIVA DA PESSOA COM DEFICIÊNCIA",
  "30.002": "002 - RECURSOS SOB A SUPERVISÃO DA SECRETARIA DE ADMINISTRAÇÃO",

  // 31 - SECRETARIA EXECUTIVA DE POLÍTICAS DE PROMOÇÃO DA IGUALDADE RACIAL
  "31.001": "001 - GABINETE DA SECRETARIA EXECUTIVA DE POLÍTICAS DE PROMOÇÃO DA IGUALDADE RACIAL",

  // 32 - SECRETARIA EXECUTIVA DE POLÍTICAS PARA MULHERES E DIVERSIDADE
  "32.001": "001 - GABINETE DA SECRETARIA EXECUTIVA DE POLÍTICAS PARA MULHERES E DIVERSIDADE",
  "32.002": "002 - RECURSOS SOB A SUPERVISÃO DA SECRETARIA DE ADMINISTRAÇÃO",

  // 33 - SECRETARIA EXECUTIVA DE COMPRAS E LICITAÇÕES
  "33.001": "001 - GABINETE DA SECRETARIA EXECUTIVA DE COMPRAS E LICITAÇÕES",

  // 34 - COORDENADORIA DA DEFESA CIVIL
  "34.001": "001 - GABINETE DA COORDENADORIA DA DEFESA CIVIL",

  // 35 - SECRETARIA DA CASA CIVIL
  "35.001": "001 - GABINETE DA SECRETARIA DA CASA CIVIL",

  // 36 - SECRETARIA DA FAMÍLIA, CIDADANIA E SEGURANÇA ALIMENTAR
  "36.001": "001 - GABINETE DA SECRETARIA DA FAMÍLIA, CIDADANIA E SEGURANÇA ALIMENTAR",
  "36.002": "002 - SECRETARIA EXECUTIVA DE SEGURANÇA ALIMENTAR E NUTRICIONAL",

  // 77 / 99 - RESERVA DE CONTINGÊNCIA
  "77.777": "777 - RESERVA DE CONTINGÊNCIA - IPMO",
  "99.999": "999 - RESERVA DE CONTINGÊNCIA - PMO",
};

/**
 * Normaliza e unifica a nomenclatura da Unidade Orçamentária,
 * corrigindo variações e duplicidades da LOA de acordo com a LDO oficial.
 */
export function normalizeUnidadeOrcamentaria(
  secCodeOrName: string | undefined,
  unitRaw: string | undefined,
  programatica?: string
): string {
  // Extrair código da Secretaria (2 dígitos)
  let secCode = "";
  if (secCodeOrName) {
    const secMatch = String(secCodeOrName).trim().match(/^(\d{1,2})/);
    if (secMatch) secCode = secMatch[1].padStart(2, "0");
  }

  // Se não encontrou no órgão, tentar extrair da programática LOA (ex: '11.001.04.122...')
  if (!secCode && programatica) {
    const progParts = String(programatica).trim().split(".");
    if (progParts.length >= 2 && /^\d+$/.test(progParts[0])) {
      secCode = progParts[0].padStart(2, "0");
    }
  }

  // Extrair código da Unidade (3 dígitos)
  let unitCode = "";
  if (unitRaw) {
    const unitMatch = String(unitRaw).trim().match(/^(\d{1,3})/);
    if (unitMatch) unitCode = unitMatch[1].padStart(3, "0");
  }

  if (!unitCode && programatica) {
    const progParts = String(programatica).trim().split(".");
    if (progParts.length >= 2 && /^\d+$/.test(progParts[1])) {
      unitCode = progParts[1].padStart(3, "0");
    }
  }

  const key = `${secCode}.${unitCode}`;

  // 1. Caso haja mapeamento direto no catálogo canônico LDO
  if (UNIDADES_ORCAMENTARIAS_LDO[key]) {
    return UNIDADES_ORCAMENTARIAS_LDO[key];
  }

  // 2. Se for unidade 001 e temos a secretaria identificada, gerar nome padrão do Gabinete
  if (unitCode === "001" && secCode && ORGAOS_LOA_NOMES[secCode]) {
    const secNome = ORGAOS_LOA_NOMES[secCode];
    if (secCode === "01" || secCode === "02") {
      return "001 - CHEFIA DE GABINETE";
    }
    return `001 - GABINETE DA ${secNome.toUpperCase()}`;
  }

  // 3. Limpar formatação do texto original (remover hífens colados, espaços duplos)
  const cleanOriginal = String(unitRaw || "").trim().replace(/\s+/g, " ");
  if (cleanOriginal) {
    const match = cleanOriginal.match(/^(\d+)\s*[-—–]\s*(.+)$/);
    if (match) {
      return `${match[1].padStart(3, "0")} - ${match[2].trim().toUpperCase()}`;
    }
    return unitCode ? `${unitCode} - ${cleanOriginal.toUpperCase()}` : cleanOriginal;
  }

  return unitCode ? `${unitCode} - UNIDADE ORÇAMENTÁRIA` : "001 - CHEFIA DE GABINETE";
}
